variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  REGISTRY_HOSTNAME: <Resistry name>
  DOCKER_IMAGE_NAME: cronicle
  DOCKER_IMAGE_PYTHON_NAME: python

image: docker:19.03.12

services:
  - docker:19.03.12-dind
  # - name: docker:19.03.12-dind
  #   entrypoint: ["env", "-u", "DOCKER_HOST"]
  #   command: ["dockerd-entrypoint.sh","--tls=false"]

stages:
  - build-base
  - build

build-base:
  image: "docker:latest"
  stage: build-base
  tags:
    - <For custom Runner>
  before_script:
    - until docker info; do sleep 1; done
  script:
    - docker info
    - docker build -f Dockerfile.base --tag $REGISTRY_HOSTNAME/$DOCKER_IMAGE_PYTHON_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $REGISTRY_HOSTNAME/DOCKER_IMAGE_PYTHON_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $REGISTRY_HOSTNAME/DOCKER_IMAGE_PYTHON_NAME:$CI_COMMIT_SHORT_SHA $REGISTRY_HOSTNAME/$DOCKER_IMAGE_PYTHON_NAME:base
    - docker push $REGISTRY_HOSTNAME/$DOCKER_IMAGE_PYTHON_NAME:base
  only:
      - main

build-main:
  image: "docker:latest"
  stage: build
  tags:
    - <For custom Runner>
  before_script:
    - until docker info; do sleep 1; done
  script:
    - docker build --tag $REGISTRY_HOSTNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $REGISTRY_HOSTNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $REGISTRY_HOSTNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA $REGISTRY_HOSTNAME/$DOCKER_IMAGE_NAME:latest
    - docker push $REGISTRY_HOSTNAME/$DOCKER_IMAGE_NAME:latest
  only:
      - main